# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - access-prd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0411d8e84ed24ab1824510566eb958a7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa572413100843228d142072a3f93be8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0411d8e84ed24ab1824510566eb958a7 }}/access:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'access-prd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_89d42a15411949ccb33c6601a36deec3 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0411d8e84ed24ab1824510566eb958a7 }}/access:${{ github.sha }}'